Create new Meatballs
peaksoft-school/giftlist-js8 pull request #10
Opened 2023-04-09 07:20 UTC by Naz-Erke18

2023-04-09 08:34 UTC, saltanatzakypova commented
Good job!

2023-04-09 08:49 UTC, yryskeldi0101 commented
checked!

2023-04-09 09:10 UTC, FrontenderO07 commented
мен эле калыптырмын. Checked!!!

2023-04-09 15:07 UTC, songhee24 requested changes

2023-04-09 15:07 UTC, songhee24 commented on src/components/UI/Meatballs.jsx
> +    const { open, handleClick, anchorEl, handleClose } = useMeatballs();
хук вызывает там где будет использоваться ваша компонента

2023-04-09 15:52 UTC, songhee24 requested changes

2023-04-09 15:52 UTC, songhee24 commented on src/components/UI/Meatballs.jsx
> +export default function Meatballs({ arrayIcon, open, handleClick, anchorEl, handleClose }) {
...restProps also needed

2023-04-11 08:56 UTC, songhee24 requested changes

2023-04-11 08:56 UTC, songhee24 commented on src/components/UI/Meatballs.jsx
> +            {...restProps}
здесь не нужно давать    {...restProps}

2023-06-27 13:28 UTC, closed without merging