Feature/checkboxes
peaksoft-school/giftlist-js8 pull request #12
Opened 2023-04-10 07:00 UTC by Begimai7

2023-04-11 10:45 UTC, songhee24 requested changes

2023-04-11 10:45 UTC, songhee24 commented on src/components/UI/Checkboxes.jsx
> +export function Checkboxes() {
reusable controlled component болуш керекк

2023-04-11 10:45 UTC, songhee24 commented on src/components/UI/Checkboxes.jsx
> +      <div>
уберите div

2023-04-12 05:21 UTC, closed without merging

2023-04-12 06:24 UTC, Naz-Erke18 commented
checked!