create checkbox
peaksoft-school/giftlist-js8 pull request #19
Opened 2023-04-12 06:18 UTC by Begimai7

2023-04-12 06:23 UTC, aielina5 commented
Cheked!

2023-04-12 06:24 UTC, yryskeldi0101 commented
Good job !

2023-04-12 07:33 UTC, songhee24 requested changes

2023-04-12 09:03 UTC, saltanatzakypova commented
Cheked!

2023-04-12 11:56 UTC, FrontenderO07 commented
Cheked. Good jod!

2023-04-13 07:34 UTC, songhee24 approved these changes

2023-04-13 07:35 UTC, merged