Feature/landing page part 1
peaksoft-school/giftlist-js8 pull request #20
Opened 2023-04-12 11:45 UTC by yryskeldi0101

2023-04-12 12:05 UTC, Begimai7 commented
checked by me

2023-04-12 12:10 UTC, FrontenderO07 commented
No problem!

2023-04-12 16:35 UTC, Naz-Erke18 commented
checked!

2023-04-13 08:27 UTC, songhee24 requested changes

2023-04-13 08:27 UTC, songhee24 commented on src/components/landing-page/LandingPage.jsx
landing page бул containers папкада болуш керек

2023-04-13 08:51 UTC, songhee24 approved these changes

2023-04-13 08:51 UTC, merged