done singIn/singUp
peaksoft-school/giftlist-js8 pull request #36
Opened 2023-04-17 11:54 UTC by FrontenderO07

2023-04-17 12:00 UTC, FrontenderO07 commented
mui icon material скачал поетому conflict как исправить?

2023-04-18 08:52 UTC, saltanatzakypova commented
checked!

2023-04-18 09:07 UTC, Naz-Erke18 commented
checked

2023-04-18 10:41 UTC, songhee24 requested changes

2023-04-18 10:41 UTC, songhee24 commented on src/assets/icons/GoogleBlack.svg
название иконок всегда должны быть lowercase

2023-04-18 10:41 UTC, songhee24 commented on src/assets/icons/GoogleBlack.svg
googleBlack

2023-04-18 10:41 UTC, songhee24 commented on src/assets/icons/Light.svg
light

2023-04-18 10:41 UTC, songhee24 commented on src/components/form/ForgotPassword.jsx
> +   const [openModal, setOpenModal] = useState(true)
открыть модалку и закрыть могут только извне

2023-04-18 10:41 UTC, songhee24 commented on src/components/form/ForgotPassword.jsx
> +const ForgotPassword = () => {
плюс нужна логика для подъема состояния

2023-04-18 10:41 UTC, songhee24 commented on src/components/form/ForgotPassword.jsx
> +      <div>
должна быть формой

2023-04-18 10:41 UTC, songhee24 commented on src/components/form/ResetPassword.jsx
> +   const [openModal, setOpenModal] = useState(true)
тут тоже самое что и сверху написал

2023-04-18 10:41 UTC, songhee24 commented on src/components/form/SingIn.jsx
> +         <form>
submit где ?

2023-04-18 10:41 UTC, songhee24 commented on src/components/form/SingIn.jsx
> +   const [openModal, setOpenModal] = useState(true)
тоже самое модал должен приходит снаружи

2023-04-18 10:41 UTC, songhee24 commented on src/components/form/SingIn.jsx
> +   const [openModal, setOpenModal] = useState(true)
как пропс

2023-04-18 10:41 UTC, songhee24 commented on src/components/form/SingIn.jsx
> +const SingIn = () => {
плюс подъем состояния  нужен

2023-04-18 10:41 UTC, songhee24 commented on src/components/form/ResetPassword.jsx
> +            <PasswordInput placeholder="Повторите пароль" />
проверка пароля совпадает ли со старым или нет

2023-05-01 08:02 UTC, songhee24 approved these changes

2023-05-01 08:02 UTC, merged