Routes 50% completed
peaksoft-school/giftlist-js8 pull request #45
Opened 2023-04-23 11:18 UTC by yryskeldi0101

2023-04-23 11:20 UTC, FrontenderO07 commented
checked!

2023-04-23 13:45 UTC, Begimai7 commented
checked

2023-04-23 13:47 UTC, saltanatzakypova commented
checked!

2023-04-25 07:12 UTC, songhee24 requested changes

2023-04-25 07:12 UTC, songhee24 commented on src/hoc/withPrivateRoute.js
> +const PrivateRoute = ({ component: Component, isAuthenticated, ...rest }) => {
isAuthenticated пропс катары эмес а сразу  PrivateRoute ичине useSelector менен алатурган эле кылып койгула

2023-04-25 07:12 UTC, songhee24 commented on src/layout/LayoutPage.jsx
> +import SideBar from '../components/side-bar/SideBar'
sidebar'ды layout болуп эсептелет header тоже самое

2023-04-25 07:12 UTC, songhee24 commented on src/layout/LayoutPage.jsx
> +         <Outlet />
main тег болсо семантикага жакшы болмок

2023-04-25 07:12 UTC, songhee24 commented on src/routes/AdminRoutes.jsx
> +         <Route path="/user" element={<Users />} />
path озунчо constant  кылсак жакшы болмок

2023-04-25 07:12 UTC, songhee24 commented on src/routes/UserRoutes.jsx
> +
ошондо тузулгон PrivateRoute кайсыл жерде иштетип калтат мен коргон жокмун

2023-04-25 17:38 UTC, songhee24 requested changes

2023-04-25 17:38 UTC, songhee24 commented on src/layout/LayoutPage.jsx
> +      <main>
разве header sidebar биз main'ге киргизебизби ?

2023-04-26 08:09 UTC, songhee24 approved these changes

2023-04-26 08:09 UTC, merged