feature/axiosInstance
peaksoft-school/giftlist-js8 pull request #46
Opened 2023-04-26 12:34 UTC by aielina5

2023-04-26 12:37 UTC, FrontenderO07 commented
checked!

2023-04-27 04:42 UTC, Begimai7 commented
checked

2023-04-27 06:52 UTC, songhee24 requested changes

2023-04-27 06:52 UTC, songhee24 commented on src/api/axiosInstance.js
> +         store.dispatch()
нужно возвращать ошибку

2023-04-27 06:52 UTC, songhee24 commented on src/api/axiosInstance.js
> +      config.headers.set('Authorization', store.getState().auth.token)
а если токена не будет

2023-04-27 15:26 UTC, Kamchybekk approved these changes

2023-04-27 15:26 UTC, merged